// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/meddhiazoghlami/leave-management/internal/config"
	"github.com/meddhiazoghlami/leave-management/internal/handlers"
	"github.com/meddhiazoghlami/leave-management/internal/obs"
	"github.com/meddhiazoghlami/leave-management/internal/server"
	"github.com/meddhiazoghlami/leave-management/internal/store"
)

// Injectors from wire.go:

// InitializeApp builds the full application (config → store → handlers → router)
// and returns it plus a cleanup func (closes the DB pool).
func InitializeApp(ctx context.Context) (*App, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	store, cleanup, err := provideStore(ctx, configConfig)
	if err != nil {
		return nil, nil, err
	}
	handlersHandlers := handlers.New(store, configConfig)
	logger, cleanup2, err := obs.NewLogger(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := obs.InitTracing(ctx, configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	engine := server.New(handlersHandlers, store, configConfig, logger, tracerProvider)
	app := &App{
		Config: configConfig,
		Store:  store,
		Router: engine,
		Logger: logger,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// InitializeStore builds just the data layer, for DB-only commands like seed.
func InitializeStore(ctx context.Context) (*store.Store, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	storeStore, cleanup, err := provideStore(ctx, configConfig)
	if err != nil {
		return nil, nil, err
	}
	return storeStore, func() {
		cleanup()
	}, nil
}
