// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
	Role         string
	ManagerID    pgtype.Int8
	CreatedAt    time.Time
}

type LeaveAllocation struct {
	ID          int64
	EmployeeID  int64
	LeaveTypeID int64
	Year        int32
	Days        int32
}

type LeaveRequest struct {
	ID          int64
	EmployeeID  int64
	LeaveTypeID int64
	StartDate   time.Time
	EndDate     time.Time
	WorkingDays int32
	Reason      string
	Status      string
	DecidedBy   pgtype.Int8
	DecidedAt   pgtype.Timestamptz
	CreatedAt   time.Time
}

type LeaveType struct {
	ID          int64
	Name        string
	DefaultDays int32
	Color       string
	CreatedAt   time.Time
}

type PublicHoliday struct {
	ID          int64
	Name        string
	HolidayDate time.Time
	CreatedAt   time.Time
}

type Session struct {
	Token      string
	EmployeeID int64
	CreatedAt  time.Time
	ExpiresAt  time.Time
}
