// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOwnRequest = `-- name: CancelOwnRequest :exec
UPDATE leave_requests
SET status = 'cancelled'
WHERE id = $1 AND employee_id = $2 AND status = 'pending'
`

type CancelOwnRequestParams struct {
	ID         int64
	EmployeeID int64
}

func (q *Queries) CancelOwnRequest(ctx context.Context, arg CancelOwnRequestParams) error {
	_, err := q.db.Exec(ctx, cancelOwnRequest, arg.ID, arg.EmployeeID)
	return err
}

const countPendingForManager = `-- name: CountPendingForManager :one
SELECT COUNT(*)
FROM leave_requests r
JOIN employees e ON e.id = r.employee_id
WHERE r.status = 'pending' AND e.manager_id = $1
`

func (q *Queries) CountPendingForManager(ctx context.Context, managerID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingForManager, managerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (name, email, password_hash, role, manager_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, password_hash, role, manager_id, created_at
`

type CreateEmployeeParams struct {
	Name         string
	Email        string
	PasswordHash string
	Role         string
	ManagerID    pgtype.Int8
}

// Employees are created by the seed program (no self-registration in scope).
func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.ManagerID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ManagerID,
		&i.CreatedAt,
	)
	return i, err
}

const createHoliday = `-- name: CreateHoliday :one
INSERT INTO public_holidays (name, holiday_date)
VALUES ($1, $2)
RETURNING id, name, holiday_date, created_at
`

type CreateHolidayParams struct {
	Name        string
	HolidayDate time.Time
}

func (q *Queries) CreateHoliday(ctx context.Context, arg CreateHolidayParams) (PublicHoliday, error) {
	row := q.db.QueryRow(ctx, createHoliday, arg.Name, arg.HolidayDate)
	var i PublicHoliday
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HolidayDate,
		&i.CreatedAt,
	)
	return i, err
}

const createLeaveRequest = `-- name: CreateLeaveRequest :one

INSERT INTO leave_requests (employee_id, leave_type_id, start_date, end_date, working_days, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, employee_id, leave_type_id, start_date, end_date, working_days, reason, status, created_at
`

type CreateLeaveRequestParams struct {
	EmployeeID  int64
	LeaveTypeID int64
	StartDate   time.Time
	EndDate     time.Time
	WorkingDays int32
	Reason      string
}

type CreateLeaveRequestRow struct {
	ID          int64
	EmployeeID  int64
	LeaveTypeID int64
	StartDate   time.Time
	EndDate     time.Time
	WorkingDays int32
	Reason      string
	Status      string
	CreatedAt   time.Time
}

// ──────────────────────────── leave_requests ─────────────────────────────
func (q *Queries) CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (CreateLeaveRequestRow, error) {
	row := q.db.QueryRow(ctx, createLeaveRequest,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.StartDate,
		arg.EndDate,
		arg.WorkingDays,
		arg.Reason,
	)
	var i CreateLeaveRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.WorkingDays,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createLeaveType = `-- name: CreateLeaveType :one
INSERT INTO leave_types (name, default_days, color)
VALUES ($1, $2, $3)
RETURNING id, name, default_days, color, created_at
`

type CreateLeaveTypeParams struct {
	Name        string
	DefaultDays int32
	Color       string
}

func (q *Queries) CreateLeaveType(ctx context.Context, arg CreateLeaveTypeParams) (LeaveType, error) {
	row := q.db.QueryRow(ctx, createLeaveType, arg.Name, arg.DefaultDays, arg.Color)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultDays,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (token, employee_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, employee_id, created_at, expires_at
`

type CreateSessionParams struct {
	Token      string
	EmployeeID int64
	ExpiresAt  time.Time
}

// ──────────────────────────────── sessions ───────────────────────────────
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Token, arg.EmployeeID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteHoliday = `-- name: DeleteHoliday :exec
DELETE FROM public_holidays WHERE id = $1
`

func (q *Queries) DeleteHoliday(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteHoliday, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, name, email, password_hash, role, manager_id, created_at
FROM employees
WHERE id = $1
`

func (q *Queries) GetEmployee(ctx context.Context, id int64) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ManagerID,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one


SELECT id, name, email, password_hash, role, manager_id, created_at
FROM employees
WHERE email = $1
`

// Phase 9: the real domain's queries. sqlc turns each annotated statement into
// a typed Go method on *Queries. Conventions worth noting:
//
//	:one/:many/:exec  -> single row / slice / no rows
//	@name / ::type    -> named params with an explicit cast, so sqlc infers the
//	                     Go type we want (and NULL-able columns don't leak
//	                     pgtype wrappers into params).
//	sqlc.embed(x)     -> return the whole `x` table struct as a nested field.
//
// Deliberately, no query SELECTs the nullable timestamp `decided_at` (nor
// `decided_by`): the global timestamptz->time.Time override would force it to a
// non-null time.Time and a NULL would fail to scan. Those columns are written
// (SetRequestStatus) but never read back into Go.
// ─────────────────────────────── employees ───────────────────────────────
func (q *Queries) GetEmployeeByEmail(ctx context.Context, email string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, email)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ManagerID,
		&i.CreatedAt,
	)
	return i, err
}

const getLeaveRequest = `-- name: GetLeaveRequest :one
SELECT id, employee_id, leave_type_id, start_date, end_date, working_days, reason, status, created_at
FROM leave_requests
WHERE id = $1
`

type GetLeaveRequestRow struct {
	ID          int64
	EmployeeID  int64
	LeaveTypeID int64
	StartDate   time.Time
	EndDate     time.Time
	WorkingDays int32
	Reason      string
	Status      string
	CreatedAt   time.Time
}

func (q *Queries) GetLeaveRequest(ctx context.Context, id int64) (GetLeaveRequestRow, error) {
	row := q.db.QueryRow(ctx, getLeaveRequest, id)
	var i GetLeaveRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.WorkingDays,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionEmployee = `-- name: GetSessionEmployee :one
SELECT e.id, e.name, e.email, e.password_hash, e.role, e.manager_id, e.created_at
FROM sessions s
JOIN employees e ON e.id = s.employee_id
WHERE s.token = $1 AND s.expires_at > now()
`

type GetSessionEmployeeRow struct {
	Employee Employee
}

// One round-trip auth lookup: valid (unexpired) token -> the full employee row.
func (q *Queries) GetSessionEmployee(ctx context.Context, token string) (GetSessionEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getSessionEmployee, token)
	var i GetSessionEmployeeRow
	err := row.Scan(
		&i.Employee.ID,
		&i.Employee.Name,
		&i.Employee.Email,
		&i.Employee.PasswordHash,
		&i.Employee.Role,
		&i.Employee.ManagerID,
		&i.Employee.CreatedAt,
	)
	return i, err
}

const listApprovedInRange = `-- name: ListApprovedInRange :many

SELECT r.id, e.name AS employee_name,
       lt.name AS leave_type_name, lt.color AS leave_type_color,
       r.start_date, r.end_date
FROM leave_requests r
JOIN employees e ON e.id = r.employee_id
JOIN leave_types lt ON lt.id = r.leave_type_id
WHERE r.status = 'approved'
  AND r.start_date <= $1::date
  AND r.end_date >= $2::date
ORDER BY r.start_date
`

type ListApprovedInRangeParams struct {
	RangeEnd   time.Time
	RangeStart time.Time
}

type ListApprovedInRangeRow struct {
	ID             int64
	EmployeeName   string
	LeaveTypeName  string
	LeaveTypeColor string
	StartDate      time.Time
	EndDate        time.Time
}

// ──────────────────────────────── calendar ───────────────────────────────
// Approved requests overlapping [range_start, range_end]. Overlap = starts on
// or before the range end AND ends on or after the range start.
func (q *Queries) ListApprovedInRange(ctx context.Context, arg ListApprovedInRangeParams) ([]ListApprovedInRangeRow, error) {
	rows, err := q.db.Query(ctx, listApprovedInRange, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedInRangeRow{}
	for rows.Next() {
		var i ListApprovedInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeName,
			&i.LeaveTypeName,
			&i.LeaveTypeColor,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalances = `-- name: ListBalances :many

SELECT lt.id AS leave_type_id, lt.name AS leave_type_name, lt.color AS leave_type_color,
       COALESCE(a.days, 0)::int AS allocated,
       COALESCE(u.used, 0)::int AS used,
       (COALESCE(a.days, 0) - COALESCE(u.used, 0))::int AS remaining
FROM leave_types lt
LEFT JOIN leave_allocations a
       ON a.leave_type_id = lt.id
      AND a.employee_id = $1
      AND a.year = $2::int
LEFT JOIN (
    SELECT leave_type_id, SUM(working_days) AS used
    FROM leave_requests
    WHERE employee_id = $1
      AND status = 'approved'
      AND EXTRACT(YEAR FROM start_date)::int = $2::int
    GROUP BY leave_type_id
) u ON u.leave_type_id = lt.id
ORDER BY lt.name
`

type ListBalancesParams struct {
	EmployeeID int64
	Year       int32
}

type ListBalancesRow struct {
	LeaveTypeID    int64
	LeaveTypeName  string
	LeaveTypeColor string
	Allocated      int32
	Used           int32
	Remaining      int32
}

// ──────────────────────────────── balances ───────────────────────────────
// Per leave type: allocated days for the year minus days already used by
// APPROVED requests in that year. LEFT JOINs so a type with no allocation and
// no usage still shows up (as 0 / 0).
func (q *Queries) ListBalances(ctx context.Context, arg ListBalancesParams) ([]ListBalancesRow, error) {
	rows, err := q.db.Query(ctx, listBalances, arg.EmployeeID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalancesRow{}
	for rows.Next() {
		var i ListBalancesRow
		if err := rows.Scan(
			&i.LeaveTypeID,
			&i.LeaveTypeName,
			&i.LeaveTypeColor,
			&i.Allocated,
			&i.Used,
			&i.Remaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT e.id, e.name, e.email, e.role, COALESCE(m.name, '') AS manager_name
FROM employees e
LEFT JOIN employees m ON m.id = e.manager_id
WHERE ($1::bigint = 0 OR e.manager_id = $1::bigint)
ORDER BY e.name
`

type ListEmployeesRow struct {
	ID          int64
	Name        string
	Email       string
	Role        string
	ManagerName string
}

// ListEmployees doubles as the manager-scoped list: pass manager_id = 0 to get
// everyone (admin view), or a real id to get just that manager's reports.
func (q *Queries) ListEmployees(ctx context.Context, managerID int64) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees, managerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.ManagerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHolidays = `-- name: ListHolidays :many

SELECT id, name, holiday_date, created_at
FROM public_holidays
ORDER BY holiday_date
`

// ─────────────────────────────── holidays ────────────────────────────────
func (q *Queries) ListHolidays(ctx context.Context) ([]PublicHoliday, error) {
	rows, err := q.db.Query(ctx, listHolidays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicHoliday{}
	for rows.Next() {
		var i PublicHoliday
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HolidayDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHolidaysInRange = `-- name: ListHolidaysInRange :many
SELECT id, name, holiday_date, created_at
FROM public_holidays
WHERE holiday_date BETWEEN $1::date AND $2::date
ORDER BY holiday_date
`

type ListHolidaysInRangeParams struct {
	RangeStart time.Time
	RangeEnd   time.Time
}

func (q *Queries) ListHolidaysInRange(ctx context.Context, arg ListHolidaysInRangeParams) ([]PublicHoliday, error) {
	rows, err := q.db.Query(ctx, listHolidaysInRange, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicHoliday{}
	for rows.Next() {
		var i PublicHoliday
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HolidayDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveTypes = `-- name: ListLeaveTypes :many

SELECT id, name, default_days, color, created_at
FROM leave_types
ORDER BY name
`

// ────────────────────────────── leave_types ──────────────────────────────
func (q *Queries) ListLeaveTypes(ctx context.Context) ([]LeaveType, error) {
	rows, err := q.db.Query(ctx, listLeaveTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaveType{}
	for rows.Next() {
		var i LeaveType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultDays,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingForManager = `-- name: ListPendingForManager :many
SELECT r.id, r.employee_id, e.name AS employee_name,
       lt.name AS leave_type_name, lt.color AS leave_type_color,
       r.start_date, r.end_date, r.working_days, r.reason, r.created_at
FROM leave_requests r
JOIN employees e ON e.id = r.employee_id
JOIN leave_types lt ON lt.id = r.leave_type_id
WHERE r.status = 'pending' AND e.manager_id = $1
ORDER BY r.created_at
`

type ListPendingForManagerRow struct {
	ID             int64
	EmployeeID     int64
	EmployeeName   string
	LeaveTypeName  string
	LeaveTypeColor string
	StartDate      time.Time
	EndDate        time.Time
	WorkingDays    int32
	Reason         string
	CreatedAt      time.Time
}

func (q *Queries) ListPendingForManager(ctx context.Context, managerID pgtype.Int8) ([]ListPendingForManagerRow, error) {
	rows, err := q.db.Query(ctx, listPendingForManager, managerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingForManagerRow{}
	for rows.Next() {
		var i ListPendingForManagerRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.LeaveTypeName,
			&i.LeaveTypeColor,
			&i.StartDate,
			&i.EndDate,
			&i.WorkingDays,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByEmployee = `-- name: ListRequestsByEmployee :many
SELECT r.id, r.leave_type_id, lt.name AS leave_type_name, lt.color AS leave_type_color,
       r.start_date, r.end_date, r.working_days, r.reason, r.status, r.created_at
FROM leave_requests r
JOIN leave_types lt ON lt.id = r.leave_type_id
WHERE r.employee_id = $1
ORDER BY r.created_at DESC
`

type ListRequestsByEmployeeRow struct {
	ID             int64
	LeaveTypeID    int64
	LeaveTypeName  string
	LeaveTypeColor string
	StartDate      time.Time
	EndDate        time.Time
	WorkingDays    int32
	Reason         string
	Status         string
	CreatedAt      time.Time
}

func (q *Queries) ListRequestsByEmployee(ctx context.Context, employeeID int64) ([]ListRequestsByEmployeeRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByEmployeeRow{}
	for rows.Next() {
		var i ListRequestsByEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.LeaveTypeID,
			&i.LeaveTypeName,
			&i.LeaveTypeColor,
			&i.StartDate,
			&i.EndDate,
			&i.WorkingDays,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRequestStatus = `-- name: SetRequestStatus :exec
UPDATE leave_requests
SET status = $1, decided_by = $2::bigint, decided_at = now()
WHERE id = $3 AND status = 'pending'
`

type SetRequestStatusParams struct {
	Status    string
	DecidedBy int64
	ID        int64
}

// Only a pending request can be decided; the guard is in the WHERE clause.
func (q *Queries) SetRequestStatus(ctx context.Context, arg SetRequestStatusParams) error {
	_, err := q.db.Exec(ctx, setRequestStatus, arg.Status, arg.DecidedBy, arg.ID)
	return err
}

const upsertAllocation = `-- name: UpsertAllocation :one

INSERT INTO leave_allocations (employee_id, leave_type_id, year, days)
VALUES ($1, $2, $3, $4)
ON CONFLICT (employee_id, leave_type_id, year)
DO UPDATE SET days = EXCLUDED.days
RETURNING id, employee_id, leave_type_id, year, days
`

type UpsertAllocationParams struct {
	EmployeeID  int64
	LeaveTypeID int64
	Year        int32
	Days        int32
}

// ─────────────────────────── leave_allocations ───────────────────────────
func (q *Queries) UpsertAllocation(ctx context.Context, arg UpsertAllocationParams) (LeaveAllocation, error) {
	row := q.db.QueryRow(ctx, upsertAllocation,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.Year,
		arg.Days,
	)
	var i LeaveAllocation
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.Year,
		&i.Days,
	)
	return i, err
}
